steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        '$_AR_REPO/app:latest',
        '--build-arg',
        '_NEXT_PUBLIC_PROJECT_ID=$PROJECT_ID',
        '--build-arg',
        '_NEXT_PUBLIC_VERTEX_API_LOCATION=${_NEXT_PUBLIC_VERTEX_API_LOCATION}',
        '--build-arg',
        '_NEXT_PUBLIC_GCS_BUCKET_LOCATION=${_NEXT_PUBLIC_GCS_BUCKET_LOCATION}',
        '--build-arg',
        '_NEXT_PUBLIC_GEMINI_MODEL=${_NEXT_PUBLIC_GEMINI_MODEL}',
        '--build-arg',
        '_NEXT_PUBLIC_PRINCIPAL_TO_USER_FILTERS=${_NEXT_PUBLIC_PRINCIPAL_TO_USER_FILTERS}',
        '--build-arg',
        '_NEXT_PUBLIC_OUTPUT_BUCKET=${_NEXT_PUBLIC_OUTPUT_BUCKET}',
        '--build-arg',
        '_NEXT_PUBLIC_TEAM_BUCKET=${_NEXT_PUBLIC_TEAM_BUCKET}',
        '--build-arg',
        '_NEXT_PUBLIC_EXPORT_FIELDS_OPTIONS_URI=${_NEXT_PUBLIC_EXPORT_FIELDS_OPTIONS_URI}',
        '.',
      ]
images:
  - $_AR_REPO/app

options:
  dynamicSubstitutions: true

substitutions:
  _AR_REPO: europe-west9-docker.pkg.dev/${PROJECT_ID}/img-studio
